### ISSUE TITLE
npm audit --audit-level low needs to pass with exit code 0

### ISSUE THREAD

**Issue by elite0226** [ixofoundation/ixo-webclient#874]

**Comment by vaibhavphutane** [comment]
We have found the following issues by running snyk cli

Tested 2195 dependencies for known issues, found 93 issues, 453 vulnerable paths.


Issues to fix by upgrading:

  Upgrade @rjsf/core@2.3.0 to @rjsf/core@3.2.1 to fix
  ✗ Prototype Pollution [Medium Severity][https://snyk.io/vuln/SNYK-JS-JSONPOINTER-1577288] in jsonpointer@4.1.0
    introduced by @rjsf/core@2.3.0 > jsonpointer@4.1.0

  Upgrade apexcharts@3.20.0 to apexcharts@3.27.0 to fix
  ✗ Cross-site Scripting (XSS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-APEXCHARTS-1300579] in apexcharts@3.20.0
    introduced by apexcharts@3.20.0
  ✗ Cross-site Scripting (XSS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-APEXCHARTS-1062708] in apexcharts@3.20.0
    introduced by apexcharts@3.20.0

  Upgrade i@0.3.6 to i@0.3.7 to fix
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-I-1726768] in i@0.3.6
    introduced by i@0.3.6

  Upgrade immer@7.0.8 to immer@9.0.6 to fix
  ✗ Prototype Pollution [Medium Severity][https://snyk.io/vuln/SNYK-JS-IMMER-1540542] in immer@7.0.8
    introduced by immer@7.0.8 and 1 other path(s)
  ✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-IMMER-1019369] in immer@7.0.8
    introduced by immer@7.0.8 and 1 other path(s)

  Upgrade lodash@4.17.20 to lodash@4.17.21 to fix
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-LODASH-1018905] in lodash@4.17.20
    introduced by lodash@4.17.20 and 35 other path(s)
  ✗ Command Injection [High Severity][https://snyk.io/vuln/SNYK-JS-LODASH-1040724] in lodash@4.17.20
    introduced by lodash@4.17.20 and 35 other path(s)

  Upgrade node-sass@4.14.1 to node-sass@7.0.0 to fix
  ✗ Regular Expression Denial of Service (ReDoS) [Low Severity][https://snyk.io/vuln/SNYK-JS-TAR-1536758] in tar@2.2.2
    introduced by node-sass@4.14.1 > node-gyp@3.8.0 > tar@2.2.2 and 3 other path(s)
  ✗ Improper Certificate Validation [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODESASS-1059081] in node-sass@4.14.1
    introduced by node-sass@4.14.1
  ✗ Denial of Service (DoS) [High Severity][https://snyk.io/vuln/SNYK-JS-TRIMNEWLINES-1298042] in trim-newlines@1.0.0
    introduced by node-sass@4.14.1 > meow@3.7.0 > trim-newlines@1.0.0
  ✗ Arbitrary File Overwrite [High Severity][https://snyk.io/vuln/SNYK-JS-TAR-1536528] in tar@2.2.2
    introduced by node-sass@4.14.1 > node-gyp@3.8.0 > tar@2.2.2 and 3 other path(s)
  ✗ Arbitrary File Overwrite [High Severity][https://snyk.io/vuln/SNYK-JS-TAR-1536531] in tar@2.2.2
    introduced by node-sass@4.14.1 > node-gyp@3.8.0 > tar@2.2.2 and 3 other path(s)
  ✗ Arbitrary File Write [High Severity][https://snyk.io/vuln/SNYK-JS-TAR-1579147] in tar@2.2.2
    introduced by node-sass@4.14.1 > node-gyp@3.8.0 > tar@2.2.2 and 3 other path(s)
  ✗ Arbitrary File Write [High Severity][https://snyk.io/vuln/SNYK-JS-TAR-1579152] in tar@2.2.2
    introduced by node-sass@4.14.1 > node-gyp@3.8.0 > tar@2.2.2 and 3 other path(s)
  ✗ Arbitrary File Write [High Severity][https://snyk.io/vuln/SNYK-JS-TAR-1579155] in tar@2.2.2
    introduced by node-sass@4.14.1 > node-gyp@3.8.0 > tar@2.2.2 and 3 other path(s)

  Upgrade npm@6.14.8 to npm@7.21.0 to fix
  ✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908] in ansi-regex@4.1.0
    introduced by @testing-library/jest-dom@4.2.4 > jest-diff@24.9.0 > pretty-format@24.9.0 > ansi-regex@4.1.0 and 19 other path(s)

  Upgrade react-scripts@3.4.1 to react-scripts@5.0.0 to fix
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-BROWSERSLIST-1090194] in browserslist@4.14.0
    introduced by react-scripts@3.4.1 > postcss-normalize@8.0.1 > browserslist@4.14.0 and 15 other path(s)
  ✗ Prototype Pollution [Medium Severity][https://snyk.io/vuln/SNYK-JS-IMMER-1540542] in immer@7.0.8
    introduced by immer@7.0.8 and 1 other path(s)
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-CSSWHAT-1298035] in css-what@2.1.3
    introduced by ixo-assistant@0.9.0 > html-webpack-plugin@3.2.0 > pretty-error@2.1.1 > renderkid@2.0.3 > css-select@1.2.0 > css-what@2.1.3 and 3 other path(s)
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-GLOBPARENT-1016905] in glob-parent@5.1.1
    introduced by react-scripts@3.4.1 > eslint@6.8.0 > glob-parent@5.1.1 and 3 other path(s)
  ✗ Reverse Tabnabbing [Medium Severity][https://snyk.io/vuln/SNYK-JS-ISTANBULREPORTS-2328088] in istanbul-reports@2.2.7
    introduced by react-scripts@3.4.1 > jest@24.9.0 > jest-cli@24.9.0 > @jest/core@24.9.0 > @jest/reporters@24.9.0 > istanbul-reports@2.2.7
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-LODASH-1018905] in lodash@4.17.20
    introduced by lodash@4.17.20 and 35 other path(s)
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-POSTCSS-1090595] in postcss@7.0.32
    introduced by react-scripts@3.4.1 > css-loader@3.4.2 > postcss@7.0.32 and 77 other path(s)
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-POSTCSS-1255640] in postcss@7.0.32
    introduced by react-scripts@3.4.1 > css-loader@3.4.2 > postcss@7.0.32 and 77 other path(s)
  ✗ Command Injection [Medium Severity][https://snyk.io/vuln/SNYK-JS-REACTDEVUTILS-1083268] in react-dev-utils@10.2.1
    introduced by react-scripts@3.4.1 > react-dev-utils@10.2.1
  ✗ Prototype Pollution [Medium Severity][https://snyk.io/vuln/SNYK-JS-OBJECTPATH-1569453] in object-path@0.11.4
    introduced by react-scripts@3.4.1 > resolve-url-loader@3.1.1 > adjust-sourcemap-loader@2.0.0 > object-path@0.11.4
  ✗ Denial of Service (DoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-SOCKJS-575261] in sockjs@0.3.19
    introduced by react-scripts@3.4.1 > webpack-dev-server@3.10.3 > sockjs@0.3.19
  ✗ Prototype Pollution [Medium Severity][https://snyk.io/vuln/SNYK-JS-YARGSPARSER-560381] in yargs-parser@11.1.1
    introduced by react-scripts@3.4.1 > webpack-dev-server@3.10.3 > yargs@12.0.5 > yargs-parser@11.1.1
  ✗ Remote Code Execution (RCE) [High Severity][https://snyk.io/vuln/SNYK-JS-SHELLQUOTE-1766506] in shell-quote@1.7.2
    introduced by react-scripts@3.4.1 > react-dev-utils@10.2.1 > shell-quote@1.7.2
  ✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908] in ansi-regex@4.1.0
    introduced by @testing-library/jest-dom@4.2.4 > jest-diff@24.9.0 > pretty-format@24.9.0 > ansi-regex@4.1.0 and 19 other path(s)
  ✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-IMMER-1019369] in immer@7.0.8
    introduced by immer@7.0.8 and 1 other path(s)
  ✗ Command Injection [High Severity][https://snyk.io/vuln/SNYK-JS-LODASH-1040724] in lodash@4.17.20
    introduced by lodash@4.17.20 and 35 other path(s)
  ✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://snyk.io/vuln/SNYK-JS-NTHCHECK-1586032] in nth-check@1.0.2
    introduced by ixo-assistant@0.9.0 > html-webpack-plugin@3.2.0 > pretty-error@2.1.1 > renderkid@2.0.3 > css-select@1.2.0 > nth-check@1.0.2 and 3 other path(s)
  ✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-OBJECTPATH-1017036] in object-path@0.11.4
    introduced by react-scripts@3.4.1 > resolve-url-loader@3.1.1 > adjust-sourcemap-loader@2.0.0 > object-path@0.11.4
  ✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-OBJECTPATH-1585658] in object-path@0.11.4
    introduced by react-scripts@3.4.1 > resolve-url-loader@3.1.1 > adjust-sourcemap-loader@2.0.0 > object-path@0.11.4
  ✗ Arbitrary Code Injection [High Severity][https://snyk.io/vuln/SNYK-JS-SERIALIZEJAVASCRIPT-570062] in serialize-javascript@2.1.2
    introduced by react-scripts@3.4.1 > terser-webpack-plugin@2.3.5 > serialize-javascript@2.1.2

  Upgrade serve@11.3.2 to serve@13.0.1 to fix
  ✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908] in ansi-regex@4.1.0
    introduced by @testing-library/jest-dom@4.2.4 > jest-diff@24.9.0 > pretty-format@24.9.0 > ansi-regex@4.1.0 and 19 other path(s)
  ✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-AJV-584908] in ajv@5.5.2
    introduced by npm@6.14.8 > libcipm@4.0.8 > npm-lifecycle@3.1.5 > node-gyp@5.1.0 > request@2.88.0 > har-validator@5.1.0 > ajv@5.5.2 and 1 other path(s)


Issues with no direct upgrade or patch:
  ✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://snyk.io/vuln/SNYK-JS-ANSIHTML-1296849] in ansi-html@0.0.7
    introduced by react-scripts@3.4.1 > webpack-dev-server@3.10.3 > ansi-html@0.0.7
  This issue was fixed in versions: 0.0.9
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-COLORSTRING-1082939] in color-string@1.5.3
    introduced by react-scripts@3.4.1 > optimize-css-assets-webpack-plugin@5.0.3 > cssnano@4.1.10 > cssnano-preset-default@4.0.7 > postcss-colormin@4.0.3 > color@3.1.2 > color-string@1.5.3
  This issue was fixed in versions: 1.5.5
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-D3COLOR-1076592] in d3-color@1.4.1
    introduced by react-vis@1.11.7 > d3-color@1.4.1 and 6 other path(s)
  This issue was fixed in versions: 3.1.0
  ✗ Remote Memory Exposure [High Severity][https://snyk.io/vuln/SNYK-JS-DNSPACKET-1293563] in dns-packet@1.3.1
    introduced by react-scripts@3.4.1 > webpack-dev-server@3.10.3 > bonjour@3.5.0 > multicast-dns@6.2.3 > dns-packet@1.3.1
  This issue was fixed in versions: 1.3.4, 5.2.4
  ✗ Cryptographic Issues [Medium Severity][https://snyk.io/vuln/SNYK-JS-ELLIPTIC-1064899] in elliptic@6.5.3
    introduced by @ixo/ixo-apimodule@1.0.9 > elliptic@6.5.3 and 5 other path(s)
  This issue was fixed in versions: 6.5.4
  ✗ Denial of Service (DoS) [High Severity][https://snyk.io/vuln/SNYK-JS-ENGINEIO-1056749] in engine.io@3.4.2
    introduced by ixo-assistant@0.9.0 > socket.io@2.3.0 > engine.io@3.4.2
  This issue was fixed in versions: 4.0.0
  ✗ Uncaught Exception [High Severity][https://snyk.io/vuln/SNYK-JS-ENGINEIO-2336356] in engine.io@4.1.1
    introduced by rasa-webchat@1.0.1 > socket.io@3.1.2 > engine.io@4.1.1
  This issue was fixed in versions: 4.1.2, 5.2.1, 6.1.1
  ✗ Information Exposure [Medium Severity][https://snyk.io/vuln/SNYK-JS-EVENTSOURCE-2823375] in eventsource@1.0.7
    introduced by ixo-assistant@0.9.0 > sockjs-client@1.5.0 > eventsource@1.0.7 and 2 other path(s)
  This issue was fixed in versions: 1.1.1, 2.0.2
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-HOSTEDGITINFO-1088355] in hosted-git-info@2.8.8
    introduced by npm@6.14.8 > hosted-git-info@2.8.8 and 4 other path(s)
  This issue was fixed in versions: 3.0.8, 2.8.9
  ✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-INI-1048974] in ini@1.3.5
    introduced by npm@6.14.8 > ini@1.3.5 and 7 other path(s)
  This issue was fixed in versions: 1.3.6
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-ISSVG-1085627] in is-svg@3.0.0
    introduced by react-scripts@3.4.1 > optimize-css-assets-webpack-plugin@5.0.3 > cssnano@4.1.10 > cssnano-preset-default@4.0.7 > postcss-svgo@4.0.2 > is-svg@3.0.0
  This issue was fixed in versions: 4.2.2
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-ISSVG-1243891] in is-svg@3.0.0
    introduced by react-scripts@3.4.1 > optimize-css-assets-webpack-plugin@5.0.3 > cssnano@4.1.10 > cssnano-preset-default@4.0.7 > postcss-svgo@4.0.2 > is-svg@3.0.0
  This issue was fixed in versions: 4.3.0
  ✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-JSONSCHEMA-1920922] in json-schema@0.2.3
    introduced by node-sass@4.14.1 > node-gyp@3.8.0 > request@2.88.2 > http-signature@1.2.0 > jsprim@1.4.1 > json-schema@0.2.3 and 2 other path(s)
  This issue was fixed in versions: 0.4.0
  ✗ Command Injection [High Severity][https://snyk.io/vuln/SNYK-JS-LODASHTEMPLATE-1088054] in lodash.template@4.5.0
    introduced by react-scripts@3.4.1 > postcss-preset-env@6.7.0 > postcss-initial@3.0.2 > lodash.template@4.5.0 and 1 other path(s)
  No upgrade or patch available
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-MARKED-174116] in marked@0.5.2
    introduced by react-md-file@2.0.0 > marked@0.5.2
  This issue was fixed in versions: 0.6.2
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-MARKED-2342073] in marked@0.5.2
    introduced by react-md-file@2.0.0 > marked@0.5.2
  This issue was fixed in versions: 4.0.10
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-MARKED-2342082] in marked@0.5.2
    introduced by react-md-file@2.0.0 > marked@0.5.2
  This issue was fixed in versions: 4.0.10
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-MARKED-451341] in marked@0.5.2
    introduced by react-md-file@2.0.0 > marked@0.5.2
  This issue was fixed in versions: 0.7.0
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-MARKED-584281] in marked@0.5.2
    introduced by react-md-file@2.0.0 > marked@0.5.2
  This issue was fixed in versions: 1.1.1
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-MARKED-73637] in marked@0.5.2
    introduced by react-md-file@2.0.0 > marked@0.5.2
  This issue was fixed in versions: 0.6.1
  ✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-MERGEDEEP-1070277] in merge-deep@3.0.2
    introduced by react-scripts@3.4.1 > @svgr/webpack@4.3.3 > @svgr/plugin-svgo@4.3.1 > merge-deep@3.0.2
  This issue was fixed in versions: 3.0.3
  ✗ Information Exposure [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODEFETCH-2342118] in node-fetch@1.7.3
    introduced by @ixo/ixo-apimodule@1.0.9 > cross-fetch@3.1.4 > node-fetch@2.6.1 and 1 other path(s)
  This issue was fixed in versions: 2.6.7, 3.1.1
  ✗ Denial of Service [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODEFETCH-674311] in node-fetch@1.7.3
    introduced by react-google-maps@9.4.5 > recompose@0.26.0 > fbjs@0.8.17 > isomorphic-fetch@2.2.1 > node-fetch@1.7.3
  This issue was fixed in versions: 2.6.1, 3.0.0-beta.9
  ✗ Open Redirect [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODEFORGE-2330875] in node-forge@0.9.0
    introduced by react-scripts@3.4.1 > webpack-dev-server@3.10.3 > selfsigned@1.10.7 > node-forge@0.9.0
  This issue was fixed in versions: 1.0.0
  ✗ Prototype Pollution [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODEFORGE-2331908] in node-forge@0.9.0
    introduced by react-scripts@3.4.1 > webpack-dev-server@3.10.3 > selfsigned@1.10.7 > node-forge@0.9.0
  This issue was fixed in versions: 1.0.0
  ✗ Improper Verification of Cryptographic Signature [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODEFORGE-2430337] in node-forge@0.9.0
    introduced by react-scripts@3.4.1 > webpack-dev-server@3.10.3 > selfsigned@1.10.7 > node-forge@0.9.0
  This issue was fixed in versions: 1.3.0
  ✗ Improper Verification of Cryptographic Signature [High Severity][https://snyk.io/vuln/SNYK-JS-NODEFORGE-2430339] in node-forge@0.9.0
    introduced by react-scripts@3.4.1 > webpack-dev-server@3.10.3 > selfsigned@1.10.7 > node-forge@0.9.0
  This issue was fixed in versions: 1.3.0
  ✗ Improper Verification of Cryptographic Signature [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODEFORGE-2430341] in node-forge@0.9.0
    introduced by react-scripts@3.4.1 > webpack-dev-server@3.10.3 > selfsigned@1.10.7 > node-forge@0.9.0
  This issue was fixed in versions: 1.3.0
  ✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-NODEFORGE-598677] in node-forge@0.9.0
    introduced by react-scripts@3.4.1 > webpack-dev-server@3.10.3 > selfsigned@1.10.7 > node-forge@0.9.0
  This issue was fixed in versions: 0.10.0
  ✗ Command Injection [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODENOTIFIER-1035794] in node-notifier@5.4.3
    introduced by react-scripts@3.4.1 > jest@24.9.0 > jest-cli@24.9.0 > @jest/core@24.9.0 > @jest/reporters@24.9.0 > node-notifier@5.4.3
  This issue was fixed in versions: 5.4.5, 8.0.2, 9.0.1
  ✗ Out-of-Bounds [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODESASS-535498] in node-sass@4.14.1
    introduced by node-sass@4.14.1
  No upgrade or patch available
  ✗ NULL Pointer Dereference [High Severity][https://snyk.io/vuln/SNYK-JS-NODESASS-535500] in node-sass@4.14.1
    introduced by node-sass@4.14.1
  No upgrade or patch available
  ✗ Out-of-bounds Read [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODESASS-540958] in node-sass@4.14.1
    introduced by node-sass@4.14.1
  No upgrade or patch available
  ✗ Uncontrolled Recursion [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODESASS-540964] in node-sass@4.14.1
    introduced by node-sass@4.14.1
  No upgrade or patch available
  ✗ Denial of Service (DoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODESASS-540978] in node-sass@4.14.1
    introduced by node-sass@4.14.1
  No upgrade or patch available
  ✗ NULL Pointer Dereference [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODESASS-540992] in node-sass@4.14.1
    introduced by node-sass@4.14.1
  No upgrade or patch available
  ✗ Out-of-Bounds [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODESASS-540998] in node-sass@4.14.1
    introduced by node-sass@4.14.1
  No upgrade or patch available
  ✗ Use After Free [High Severity][https://snyk.io/vuln/SNYK-JS-NODESASS-541000] in node-sass@4.14.1
    introduced by node-sass@4.14.1
  No upgrade or patch available
  ✗ Out-of-bounds Read [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODESASS-541002] in node-sass@4.14.1
    introduced by node-sass@4.14.1
  No upgrade or patch available
  ✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://snyk.io/vuln/SNYK-JS-NPMUSERVALIDATE-1019352] in npm-user-validate@1.0.0
    introduced by npm@6.14.8 > npm-user-validate@1.0.0
  This issue was fixed in versions: 1.0.1
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-PATHPARSE-1077067] in path-parse@1.0.6
    introduced by react-scripts@3.4.1 > resolve@1.15.0 > path-parse@1.0.6 and 4 other path(s)
  This issue was fixed in versions: 1.0.7
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-PROMPTS-1729737] in prompts@2.3.2
    introduced by react-scripts@3.4.1 > jest@24.9.0 > jest-cli@24.9.0 > prompts@2.3.2
  This issue was fixed in versions: 2.4.2
  ✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-PROTOBUFJS-2441248] in protobufjs@6.10.2
    introduced by @cosmjs/proto-signing@0.26.0 > cosmjs-types@0.2.0 > protobufjs@6.11.2 and 5 other path(s)
  This issue was fixed in versions: 6.11.3
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-RAMDA-1582370] in ramda@0.27.1
    introduced by ixo-assistant@0.9.0 > react-markdown@4.3.1 > html-to-react@1.4.3 > ramda@0.27.1 and 1 other path(s)
  This issue was fixed in versions: 0.27.2
  ✗ Insecure Defaults [Medium Severity][https://snyk.io/vuln/SNYK-JS-SOCKETIO-1024859] in socket.io@2.3.0
    introduced by ixo-assistant@0.9.0 > socket.io@2.3.0
  This issue was fixed in versions: 2.4.0
  ✗ Denial of Service (DoS) [High Severity][https://snyk.io/vuln/SNYK-JS-SOCKETIOPARSER-1056752] in socket.io-parser@3.3.0
    introduced by ixo-assistant@0.9.0 > socket.io@2.3.0 > socket.io-client@2.3.0 > socket.io-parser@3.3.0
  This issue was fixed in versions: 3.3.2, 3.4.1
  ✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://snyk.io/vuln/SNYK-JS-SSRI-1246392] in ssri@7.1.0
    introduced by npm@6.14.8 > ssri@6.0.1 and 6 other path(s)
  This issue was fixed in versions: 6.0.2, 7.1.1, 8.0.1
  ✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://snyk.io/vuln/SNYK-JS-TMPL-1583443] in tmpl@1.0.4
    introduced by react-scripts@3.4.1 > babel-jest@24.9.0 > @jest/transform@24.9.0 > jest-haste-map@24.9.0 > sane@4.1.0 > walker@1.0.7 > makeerror@1.0.11 > tmpl@1.0.4
  This issue was fixed in versions: 1.0.5
  ✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://snyk.io/vuln/SNYK-JS-TRIM-1017038] in trim@0.0.1
    introduced by ixo-assistant@0.9.0 > react-markdown@4.3.1 > remark-parse@5.0.0 > trim@0.0.1 and 1 other path(s)
  This issue was fixed in versions: 0.0.3
  ✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://snyk.io/vuln/SNYK-JS-UAPARSERJS-1023599] in ua-parser-js@0.7.21
    introduced by react-google-maps@9.4.5 > recompose@0.26.0 > fbjs@0.8.17 > ua-parser-js@0.7.21
  This issue was fixed in versions: 0.7.23
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-UAPARSERJS-1072471] in ua-parser-js@0.7.21
    introduced by react-google-maps@9.4.5 > recompose@0.26.0 > fbjs@0.8.17 > ua-parser-js@0.7.21
  This issue was fixed in versions: 0.7.24
  ✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://snyk.io/vuln/SNYK-JS-UAPARSERJS-610226] in ua-parser-js@0.7.21
    introduced by react-google-maps@9.4.5 > recompose@0.26.0 > fbjs@0.8.17 > ua-parser-js@0.7.21
  This issue was fixed in versions: 0.7.22
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-UGLIFYJS-1727251] in uglify-js@3.4.10
    introduced by ixo-assistant@0.9.0 > html-webpack-plugin@3.2.0 > html-minifier@3.5.21 > uglify-js@3.4.10 and 1 other path(s)
  This issue was fixed in versions: 3.14.3
  ✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-UNSETVALUE-2400660] in unset-value@1.0.0
    introduced by react-scripts@3.4.1 > babel-jest@24.9.0 > @jest/transform@24.9.0 > jest-haste-map@24.9.0 > anymatch@2.0.0 > micromatch@3.1.10 > braces@2.3.2 > snapdragon@0.8.2 > base@0.11.2 > cache-base@1.0.1 > unset-value@1.0.0
  This issue was fixed in versions: 2.0.1
  ✗ Authorization Bypass [Medium Severity][https://snyk.io/vuln/SNYK-JS-URLPARSE-2407759] in url-parse@1.5.7
    introduced by ixo-assistant@0.9.0 > sockjs-client@1.5.0 > url-parse@1.5.7 and 5 other path(s)
  This issue was fixed in versions: 1.5.8
  ✗ Improper Input Validation [High Severity][https://snyk.io/vuln/SNYK-JS-URLPARSE-2407770] in url-parse@1.5.7
    introduced by ixo-assistant@0.9.0 > sockjs-client@1.5.0 > url-parse@1.5.7 and 5 other path(s)
  This issue was fixed in versions: 1.5.9
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-WS-1296835] in ws@6.2.1
    introduced by @cosmjs/stargate@0.26.0 > @cosmjs/tendermint-rpc@0.26.0 > @cosmjs/socket@0.26.0 > ws@7.3.1 and 6 other path(s)
  This issue was fixed in versions: 7.4.6, 6.2.2, 5.2.3
  ✗ Arbitrary Code Injection [High Severity][https://snyk.io/vuln/SNYK-JS-XMLHTTPREQUESTSSL-1082936] in xmlhttprequest-ssl@1.5.5
    introduced by react-rasa-assistant@0.3.0 > socket.io-client@2.4.0 > engine.io-client@3.5.0 > xmlhttprequest-ssl@1.5.5 and 1 other path(s)
  This issue was fixed in versions: 1.6.2
  ✗ Access Restriction Bypass [High Severity][https://snyk.io/vuln/SNYK-JS-XMLHTTPREQUESTSSL-1255647] in xmlhttprequest-ssl@1.5.5
    introduced by react-rasa-assistant@0.3.0 > socket.io-client@2.4.0 > engine.io-client@3.5.0 > xmlhttprequest-ssl@1.5.5 and 1 other path(s)
  This issue was fixed in versions: 1.6.1
  ✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-Y18N-1021887] in y18n@4.0.0
    introduced by qrcode@1.4.4 > yargs@13.3.2 > y18n@4.0.0 and 8 other path(s)
  This issue was fixed in versions: 3.2.2, 4.0.1, 5.0.5
`

**Comment by vaibhavphutane** [comment]
![image](https://user-images.githubusercontent.com/14000470/170744134-747c6bd1-69fc-4660-8afe-e942978be578.png)
![image](https://user-images.githubusercontent.com/14000470/170744193-5e4a27d2-45a9-42bd-b84a-801471f13c87.png)
![image](https://user-images.githubusercontent.com/14000470/170744283-0f42b14e-9578-4289-8d49-24421b884c2a.png)
